### ISSUE TITLE
WYSIWYG

### ISSUE THREAD

**Issue by matuskopo** [emencia/emencia-django-newsletter#11]
Hi,

do you plan to put there any WYSIWYG editor for newsletter's body editing?
If not, I'll put it on my own ;)

**Comment by Fantomas42** [comment]
Hi,

no I don't plan to adding any WYSIWYG editor the newsletter's body.
Because it can be done easily by customizing the admin class.

Here a simple example. :

admin.site.unregister(Newsletter)

class NewsletterTinyMCEForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 150, 'rows': 80}))

```
class Meta:
model = Newsletter
```

class NewsletterTinyMCE(NewsletterAdmin):
    form = NewsletterTinyMCEForm

admin.site.register(Newsletter, NewsletterTinyMCE)

Thank you for your support.
