### ISSUE TITLE
send_newsletter command not available

### ISSUE THREAD

**Issue by aledr** [emencia/emencia-django-newsletter#18]
I followed install instructions but send_newsletter command is not available.

Thanks.

> python manage.py send_newsletter
> Unknown command: 'send_newsletter'
> Type 'manage.py help' for usage.

**Comment by lucalenardi** [comment]
Have you checked your PAYTHONPATH? Are you sure that edn is correctly installed? Can you post a little more information about your environment (versions, software stack etc.)?

**Comment by aledr** [comment]
openSUSE 11.3 x86_64:

python-2.6.5
python-django-1.2.4
python-emencia_django_newsletter-0.1

https://gist.github.com/756420

Thanks

**Comment by Fantomas42** [comment]
Hi,
if I remember well I have already experienced this issue in a special case.

Try to patch your django code with that :
https://gist.github.com/757080

The file to patch is :
django/core/management/__init__.py

Tell me if it works.

**Comment by aledr** [comment]
Yes, It worked...

Thanks.

**Comment by marconius** [comment]
I had this same issue and originally fixed it with the proposed patch, but then I realized that I had installed edn with :

  $ pip install emencia.django.newsletter

instead of the command written in the installation instructions :

  $ pip install -e git://github.com/Fantomas42/emencia-django-newsletter.git#egg=emencia.django.newsletter

I uninstalled edn and reinstalled it with the prescribed pip command, and now send_newsletter is available and I don't need to patch Django

**Comment by craigkerstiens** [comment]
There still seems to be something off with the namespacing. The below actually uses a checkout and a symlink when installing. Per pip this is not necessarily the ideal to install:

pip install -e git://github.com/Fantomas42/emencia-django-newsletter.git#egg=emencia.django.newsletter 

Instead if installing from git you should be able to:

pip install git+git://github.com/Fantomas42/emencia-django-newsletter.git#egg=emencia.django.newsletter 

This however does not work as does the repo from PyPi. These would be the two more correct ways to install, yet it prevents functionality.
